#!/bin/bash

echo "========================================"
echo "  Pastiera - Android Keyboard IME"
echo "========================================"
echo ""
echo "This is an Android Input Method Editor (IME) application"
echo "designed for devices with physical keyboards."
echo ""
echo "Project: Pastiera v0.85"
echo "Language: Kotlin"
echo "Min SDK: Android 10 (API 29)"
echo "Target SDK: Android 36"
echo ""
echo "To build this project:"
echo "  ./gradlew assembleDebug       - Build debug APK"
echo "  ./gradlew assembleStableDebug - Build stable flavor debug APK"
echo ""
echo "To run unit tests:"
echo "  ./gradlew :app:testDebugUnitTest"
echo ""
echo "The built APK can be found at:"
echo "  app/build/outputs/apk/debug/app-debug.apk"
echo ""
echo "Installation requires an Android device or emulator."
echo "See README.md for full installation instructions."
echo ""
echo "========================================"
echo "  Project is ready for Android development"
echo "========================================"
